# Generated by Django 4.0rc1 on 2021-12-22 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_api', '0007_alter_user_profile_picture'),
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontents',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocontents',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_by_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videocontents',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocontents',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/%y'),
        ),
        migrations.AddField(
            model_name='videocontents',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videocontents',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='auth_api.user'),
        ),
        migrations.AlterField(
            model_name='videocontents',
            name='video_file',
            field=models.FileField(upload_to='blog_videos/%y'),
        ),
    ]
