# Generated by Django 4.0rc1 on 2022-01-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_api', '0007_alter_user_profile_picture'),
        ('blog_api', '0002_videocontents_length_videocontents_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontents',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videocontents',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_videos', to='auth_api.user'),
        ),
        migrations.AlterField(
            model_name='videocontents',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog_videos/thumbnails/%y'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='blog_posts/header_image/')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_body', models.TextField(blank=True, max_length=1500)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('privacy', models.CharField(default='public', max_length=50)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('tags', models.TextField(blank=True, null=True)),
                ('liked_by', models.ManyToManyField(related_name='liked_blogs', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_blogs', to='auth_api.user')),
            ],
        ),
    ]
