# Generated by Django 4.0rc1 on 2021-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedsetting',
            name='countries',
            field=models.CharField(blank=True, max_length=900),
        ),
        migrations.AlterField(
            model_name='newsfeedsetting',
            name='keywords',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='newsfeedsetting',
            name='sources',
            field=models.CharField(blank=True, max_length=900),
        ),
    ]
